### ISSUE TITLE
Undo/Redo Support

### ISSUE THREAD

**Issue by 01010111** [01010111/ZOME#6]
**Describe the solution you'd like**
Undo and Redo support

**Blocks**
Right now I modify the tilemap every frame if mouse is pressed, so it would eat up an array of states

**Comment by 01010111** [comment]
Tried this for a bit with no luck :(

**Comment by PXshadow** [comment]
link the commit when you get it setup.

**Comment by 01010111** [comment]
@PXshadow it's done but sorta messy :P
